#
# This docker image is for launching test purpose presto cluster.
#

FROM openjdk:11-slim
LABEL maintainer="saj1th"

ARG VERSION
# these two arg need to be filled in as:
#
#  PrestoDB:
#
#    PKG_REPO_SUBPATH=com/facebook/presto
#    PRESTVAR=presto
#
#  Trino (at least 359 onward):
#
#    PKG_REPO_SUBPATH=io/trino
#    PRESTVAR=trino
#
#
ARG PKG_REPO_SUBPATH
ARG PRESTVAR

ENV PRESTO_VERSION="${VERSION}"
ENV PRESTO_HOME=/usr/local/"${PRESTVAR}"
#ENV BASE_URL=https://repo1.maven.org/maven2

# install dev tools
RUN apt-get update
RUN apt-get install -y \
    curl \
    tar \
    sudo \
    rsync \
    python \
    wget \
    python3-pip \
    python-dev \
    build-essential \
    uuid-runtime \
    less

RUN apt-get install -y  python-is-python3   

RUN pip install jinja2

ENV JAVA_HOME /usr/java/default
ENV PATH $PATH:$JAVA_HOME/bin

WORKDIR /usr/local/bin
ADD ${PRESTVAR}-cli-${PRESTO_VERSION}-executable.jar /usr/local/bin
RUN chmod +x ${PRESTVAR}-cli-${PRESTO_VERSION}-executable.jar
RUN mv ${PRESTVAR}-cli-${PRESTO_VERSION}-executable.jar ${PRESTVAR}-cli

WORKDIR /usr/local
ADD ${PRESTVAR}-server-${PRESTO_VERSION}.tar.gz /usr/local
#RUN tar xvzf ${PRESTVAR}-server-${PRESTO_VERSION}.tar.gz -C /usr/local/
RUN ln -s /usr/local/${PRESTVAR}-server-${PRESTO_VERSION} $PRESTO_HOME

COPY scripts-${PRESTVAR} ${PRESTO_HOME}/scripts

WORKDIR /usr/local/deltalake

ADD boston-housing /usr/local/deltalake/boston-housing

# Create data dir
RUN mkdir -p $PRESTO_HOME/data
VOLUME ["$PRESTO_HOME/data"]
