#
# Settings cribbed from _Trino: The Definitive Guide_, chapter 12
#
# Only use/reference implemented properties. Superfluous properties will be detected and prevent node startup.
#
# Important:
#   CONFIGPROPERTIES values use the unit GB
#   JVMCONFIG values use the unit G
#
# Version-dependency:
#   - Trino 369 deprecated query.max-total-memory-per-node 
#   - Keeping the feeder variable (PX_CONFIGPROPERTIES_QUERYMAXTOTALMEMORYPERNODE) here is
#     ok but the confd tmpl/toml must be (and has been) updated. 
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-px-clusterproperties
data:
  PX_CONFIGPROPERTIES_QUERYMAXMEMORYPERNODE: 13GB
  PX_CONFIGPROPERTIES_QUERYMAXMEMORY: 50GB
  PX_CONFIGPROPERTIES_QUERYMAXTOTALMEMORY: 60GB
  PX_CONFIGPROPERTIES_MEMORYHEAPHEADROOMPERNODE: 9GB
  PX_JVMCONFIG_COORDINATORMAXHEAPSIZE: 38G
  PX_JVMCONFIG_WORKERMAXHEAPSIZE: 38G

  TRINO_DELTAS3_METADATACACHETTL: FOO
  TRINO_DELTAS3_METADATALIVEFILESCACHESIZE: FOO
  TRINO_DELTAS3_DOMAINCOMPACTIONTHRESHOLD: FOO
  TRINO_DELTAS3_MAXOUTSTANDINGSPLITS: FOO
  TRINO_DELTAS3_MAXSPLITSPERSECOND: FOO
  TRINO_DELTAS3_MAXINITIALSPLITS: FOO
  TRINO_DELTAS3_MAXINITIALSPLITSIZE: FOO
  TRINO_DELTAS3_MAXSPLITSIZE: FOO
  TRINO_DELTAS3_MAXPARTITIONSPERWRITER: FOO
  TRINO_DELTAS3_ENABLENONCONCURRENTWRITES: FOO
  TRINO_DELTAS3_DEFAULTCHECKPOINTWRITINGINTERVAL: FOO
  TRINO_DELTAS3_EXPERIMENTALIGNORECHECKPOINTWRITEFAILURES: FOO
  TRINO_DELTAS3_VACUUMMINRETENTION: FOO
  TRINO_DELTAS3_HIVECATALOGNAME: FOO
  TRINO_DELTAS3_CHECKPOINTROWSTATISTICSWRITINGENABLED: FOO
  TRINO_DELTAS3_TABLESTATISTICSENABLED: FOO
  TRINO_DELTAS3_EXTENDEDSTATISTICSENABLED: FOO
  TRINO_DELTAS3_COMPRESSIONCODEC: FOO
