version: '3'

#
# Take care to use the appropriate connector name in the .properties files!
#
services:
  coordinator:
    image: "${DOCKERHUB_ID}/${PRESTVAR}-dbx-coordinator:${PRESTO_VERSION}"
    ports:
      - "8080:8080"
    container_name: "coordinator"
    volumes:
      # - ./deltas3g.properties:/usr/local/${PRESTVAR}-server-${PRESTO_VERSION}/etc/catalog/deltas3g.properties:ro
      - ./deltas3.properties:/usr/local/${PRESTVAR}-server-${PRESTO_VERSION}/etc/catalog/deltas3.properties:ro
    command: http://coordinator:8080 coordinator
    env_file:
      - _nodeconfig.env
    deploy:
      resources:
        limits:
          memory: 4G
  # worker0 really needs 5G to reliably stay up
  worker0:
    image: "${DOCKERHUB_ID}/${PRESTVAR}-dbx-worker:${PRESTO_VERSION}"
    container_name: "worker0"
    volumes:
      # - ./deltas3g.properties:/usr/local/${PRESTVAR}-server-${PRESTO_VERSION}/etc/catalog/deltas3g.properties:ro
      - ./deltas3.properties:/usr/local/${PRESTVAR}-server-${PRESTO_VERSION}/etc/catalog/deltas3.properties:ro
    ports:
      - "8081:8081"
    command: http://coordinator:8080 worker0
    env_file:
      - _nodeconfig.env
    deploy:
      resources:
        limits:
          memory: 5G
