version: '3'

services:
  coordinator:
    image: "${DOCKERHUB_ID}/${PRESTVAR}-dbx-coordinator:${PRESTO_VERSION}"
    ports:
      - "8080:8080"
    container_name: "coordinator"
    command: http://coordinator:8080 coordinator
    env_file:
      - _configproperties.env
      - _awscred.env
    deploy:
      resources:
        limits:
          memory: 2G
  worker0:
    image: "${DOCKERHUB_ID}/${PRESTVAR}-dbx-worker:${PRESTO_VERSION}"
    container_name: "worker0"
    ports:
      - "8081:8081"
    command: http://coordinator:8080 worker0
    env_file:
      - _configproperties.env
      - _awscred.env
    deploy:
      resources:
        limits:
          memory: 5G
