#
# Settings for a reasonable cluster with 8GB per node and capping out at 60GB for the entire query
# This set keeps Trino's partitioning pruning feature ON
#
# Note the PX_DELTAS3_ settings will be use recognized by Trino, not PrestoDB
# Only use/reference these in a Trino .properties file!
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-px-clusterproperties
data:
  PX_CONFIGPROPERTIES_QUERYMAXMEMORYPERNODE: 14GB
  PX_CONFIGPROPERTIES_QUERYMAXTOTALMEMORYPERNODE: 19GB
  PX_CONFIGPROPERTIES_QUERYMAXMEMORY: 50GB
  PX_CONFIGPROPERTIES_QUERYMAXTOTALMEMORY: 64GB
  PX_JVMCONFIG_COORDINATORMAXHEAPSIZE: 28G
  PX_JVMCONFIG_WORKERMAXHEAPSIZE: 28G
  PX_DELTAS3_MAXSPLITSBATCHSIZE: "200"
