#
# Settings for a local Minikube cluster. The limits are set low for a 16GB machine. You will
#  likely need to revisit the StatefulSet's spec.template.spec.containers.resources.requests/limits 
#
# This set keeps Trino's partitioning pruning feature ON
#
# Note the PX_DELTAS3_ settings will be use recognized by Trino, not PrestoDB
# Only use/reference these in a Trino .properties file!
#
# Caution: PX_JVMCONFIG settings are quoted in "G": 16G
# PX_CONFIGPROPERTIES settings are qouted in "GB": 16GB
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-px-clusterproperties
data:
  PX_CONFIGPROPERTIES_QUERYMAXMEMORYPERNODE: 2GB
  PX_CONFIGPROPERTIES_QUERYMAXTOTALMEMORYPERNODE: 5GB
  PX_CONFIGPROPERTIES_QUERYMAXMEMORY: 8GB
  PX_CONFIGPROPERTIES_QUERYMAXTOTALMEMORY: 8GB
  PX_JVMCONFIG_COORDINATORMAXHEAPSIZE: 16G
  PX_JVMCONFIG_WORKERMAXHEAPSIZE: 16G
  PX_DELTAS3_MAXSPLITSBATCHSIZE: "200"
