#
# Settings cribbed from _Trino: The Definitive Guide_, chapter 12
#
# Only use/reference implemented properties. Superfluous properties will be detected and prevent node startup.
#
# Important:
#   CONFIGPROPERTIES values use the unit GB
#   JVMCONFIG values use the unit G
#
# Version-dependency:
#   - Trino 369 deprecated query.max-total-memory-per-node 
#   - Keeping the feeder variable (PX_CONFIGPROPERTIES_QUERYMAXTOTALMEMORYPERNODE) here is
#     ok but the confd tmpl/toml must be (and has been) updated. 
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-px-clusterproperties
data:
  PX_CONFIGPROPERTIES_QUERYMAXMEMORYPERNODE: 13GB
  PX_CONFIGPROPERTIES_QUERYMAXTOTALMEMORYPERNODE: 16GB
  PX_CONFIGPROPERTIES_QUERYMAXMEMORY: 50GB
  PX_CONFIGPROPERTIES_QUERYMAXTOTALMEMORY: 60GB
  PX_CONFIGPROPERTIES_MEMORYHEAPHEADROOMPERNODE: 9GB
  PX_JVMCONFIG_COORDINATORMAXHEAPSIZE: 38G
  PX_JVMCONFIG_WORKERMAXHEAPSIZE: 38G
  PX_DELTAS3_MAXSPLITSBATCHSIZE: "200"
