#
# Settings appropriate for Trino 373 & onward's OSS Delta connector
#
# These settings are exclusive to Trino's Delta Lake connector and
#  distinct from PrestoDB's Delta connector.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-trino-deltalakeconnector-config
data:
  TRINO_DELTALAKE_METADATACACHETTL: FOO
  TRINO_DELTALAKE_METADATALIVEFILESCACHESIZE: FOO
  TRINO_DELTALAKE_DOMAINCOMPACTIONTHRESHOLD: FOO
  TRINO_DELTALAKE_MAXOUTSTANDINGSPLITS: FOO
  TRINO_DELTALAKE_MAXSPLITSPERSECOND: FOO
  TRINO_DELTALAKE_MAXINITIALSPLITS: FOO
  TRINO_DELTALAKE_MAXINITIALSPLITSIZE: FOO
  TRINO_DELTALAKE_MAXSPLITSIZE: FOO
  TRINO_DELTALAKE_MAXPARTITIONSPERWRITER: FOO
  TRINO_DELTALAKE_ENABLENONCONCURRENTWRITES: FOO
  TRINO_DELTALAKE_DEFAULTCHECKPOINTWRITINGINTERVAL: FOO
  TRINO_DELTALAKE_EXPERIMENTALIGNORECHECKPOINTWRITEFAILURES: FOO
  TRINO_DELTALAKE_VACUUMMINRETENTION: FOO
  TRINO_DELTALAKE_HIVECATALOGNAME: FOO
  TRINO_DELTALAKE_CHECKPOINTROWSTATISTICSWRITINGENABLED: FOO
  TRINO_DELTALAKE_TABLESTATISTICSENABLED: FOO
  TRINO_DELTALAKE_EXTENDEDSTATISTICSENABLED: FOO
  TRINO_DELTALAKE_COMPRESSIONCODEC: FOO
