ARG VERSION
ARG DOCKERHUB_ID

FROM ${DOCKERHUB_ID}/trino-base:${VERSION}
LABEL maintainer="overcoil"

COPY etc /usr/local/px/etc
COPY px-etc-catalog-delta.properties /usr/local/px/etc/catalog/delta.properties
EXPOSE 8081

WORKDIR /usr/local/px
ENTRYPOINT [ "./scripts/px-prep.sh" ]
