#
# k8s yaml for Trino coordinators:
#   1 StatefulSet - use a StatefulSet to get a sticky/persistent name for each Trino node (pod)
#   1 Service - a headless service for the worker pool 
#   1 Service Account - access control
#
# The secret is passed in to configure deltas3.properties dynamically for reading S3 Delta tables
#
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    app: trino
    version: v359
spec:
  selector:
    app: trino
  clusterIP: None
  ports:
  - port: 8080
    name: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-coordinator
  labels:
    account: SVC_C
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coordinator
spec:
  selector:
    matchLabels:
      app: trino
      version: v359
  serviceName: coordinator
  replicas: 1
  template:
    metadata:
      labels:
        app: trino
        version: v359
    spec:
      containers:
      - name: coordinator
        image: docker.io/overcoil/trino-dbx-coordinator:359
        ports:
        - containerPort: 8080
          name: access
        resources:
          requests:
            memory: "4G"
            cpu: "1000m"
          limits:
            memory: "5G"
            cpu: "1000m"
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PX_CONFIGPROPERTIES_QUERYMAXMEMORYPERNODE
            value: 8GB
          - name: PX_CONFIGPROPERTIES_QUERYMAXTOTALMEMORYPERNODE
            value: 8GB
          - name: PX_CONFIGPROPERTIES_QUERYMAXMEMORY
            value: 50GB
          - name: PX_CONFIGPROPERTIES_QUERYMAXTOTALMEMORY
            value: 60GB
          - name: PX_DELTAS3_PARTITIONPRUNINGENABLED
            value: "true"
          - name: PX_DELTAS3_FILTERPUSHDOWNENABLED
            value: "true"
          - name: PX_DELTAS3_PROJECTIONPUSHDOWNENABLED
            value: "true"
        envFrom:
        - configMapRef:
            name: cm-px-clusterproperties
        - secretRef:
            name: secret-awscred
        command: ["./scripts/px-prep.sh"]
        args: ["http://coordinator-0.coordinator.trino.svc.cluster.local:8080", $(node.name)]
        imagePullPolicy: Always
      dnsConfig:
        searches:
          - worker.trino.svc.cluster.local
