#
# For canonical build 0.269
#
# k8s yaml for PrestoDB coordinators:
#   1 StatefulSet - use a StatefulSet to get a sticky/persistent name for each PrestoDB node (pod)
#   1 Service - a headless service for the worker pool 
#   1 Service Account - access control
#
# The secret is passed in to configure deltas3.properties dynamically for reading S3 Delta tables
#
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    app: prestodb
    version: v0269
spec:
  selector:
    app: prestodb
    version: v0269
  clusterIP: None
  ports:
  - port: 8080
    name: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-coordinator
  labels:
    account: SVC_C
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coordinator
spec:
  selector:
    matchLabels:
      app: prestodb
      version: v0269
  serviceName: coordinator
  replicas: 1
  template:
    metadata:
      labels:
        app: prestodb
        version: v0269
        role: px-coord
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - px-coord
      containers:
      - name: coordinator
        image: docker.io/overcoil/presto-dbx-coordinator:0.269-SNAPSHOT
        ports:
        - containerPort: 8080
          name: access
        # resources:
        #   requests:
        #     memory: "4G"
        #     cpu: "1000m"
        #   limits:
        #     memory: "8G"
        #     cpu: "1000m"
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: cm-px-clusterproperties
        - secretRef:
            name: secret-awscred
        command: ["./scripts/px-prep.sh"]
        args: ["http://coordinator-0.coordinator.prestodb.svc.cluster.local:8080", $(node.name)]
        imagePullPolicy: Always
      dnsConfig:
        searches:
          - worker.prestodb.svc.cluster.local
