#
# For build 373 & onward (373 as the initial OSS release of Starburst's Delta connector)
#
# k8s yaml for Trino coordinators:
#   1 StatefulSet - use a StatefulSet to get a sticky/persistent name for each Trino node (pod)
#   1 Service - a headless service for the worker pool 
#   1 Service Account - access control
#
# The secret is passed in to configure deltas3.properties dynamically for reading S3 Delta tables
#
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    app: trino
    version: v373
spec:
  selector:
    app: trino
  clusterIP: None
  ports:
  - port: 8080
    name: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-coordinator
  labels:
    account: SVC_C
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coordinator
spec:
  selector:
    matchLabels:
      app: trino
      version: v373
  serviceName: coordinator
  replicas: 1
  template:
    metadata:
      labels:
        app: trino
        version: v373
        role: px-coord
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - px-coord
      containers:
      - name: coordinator
        image: docker.io/overcoil/trino-dbx-coordinator:374
        ports:
        - containerPort: 8080
          name: access
        # resources:
        #   requests:
        #     memory: "16G"
        #     cpu: "1000m"
        #   limits:
        #     memory: "16G"
        #     cpu: "1000m"
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: cm-px-nodeconfig
        command: ["./scripts/px-prep.sh"]
        args: ["http://coordinator-0.coordinator.trino.svc.cluster.local:8080", $(node.name)]
        imagePullPolicy: Always
        volumeMounts:
        - name: deltas3g-file
          mountPath: /usr/local/px/etc/catalog
          readOnly: true
      volumes:
      - name: deltas3g-file
        configMap:
          name: cm-deltas3g.properties
      dnsConfig:
        searches:
          - worker.trino.svc.cluster.local
