ARG VERSION
ARG DOCKERHUB_ID

FROM ${DOCKERHUB_ID}/presto-base:${VERSION}

# TODO: I couldn't get ARG/ENV to work properly to externalize/parameterize PRESTVAR 

LABEL maintainer="saj1th"

COPY etc /usr/local/presto/etc
COPY etc-catalog-delta-presto.properties /usr/local/presto/etc/catalog/delta.properties

RUN ls -laR /usr/local/presto/etc/

EXPOSE 8080

WORKDIR /usr/local/presto
ENTRYPOINT ["./scripts/presto.sh"]
