ARG VERSION
ARG DOCKERHUB_ID

FROM ${DOCKERHUB_ID}/trino-base:${VERSION}

# TODO: I couldn't get ARG/ENV to work properly to externalize/parameterize PRESTVAR 

LABEL maintainer="saj1th"

COPY etc /usr/local/trino/etc
COPY etc-catalog-delta-trino.properties /usr/local/trino/etc/catalog/delta.properties

RUN ls -laR /usr/local/trino/etc/

EXPOSE 8080

WORKDIR /usr/local/trino
ENTRYPOINT ["./scripts/trino.sh"]
