ARG VERSION
ARG DOCKERHUB_ID

FROM ${DOCKERHUB_ID}/trino-base:${VERSION}

# TODO: I couldn't get ARG/ENV to work properly to externalize/parameterize PRESTVAR 

LABEL maintainer="overcoil"

COPY etc /usr/local/px/etc
COPY px-etc-catalog-delta.properties /usr/local/px/etc/catalog/delta.properties

RUN ls -laR /usr/local/px/etc/

EXPOSE 8080

WORKDIR /usr/local/px
ENTRYPOINT ["./scripts/px-prep.sh"]
